### ISSUE TITLE
Add lint command

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#117]
- PPN Validation: https://github.com/gbv/pica-data-js/blob/b3a59d44c3b88892a623bf40296cf8d17acfd883/src/pica.js#L137
- Avram lint (depends on #288)

**Comment by nichtich** [comment]
See also also validation of PICA [by checking against an Avram Schema](https://pro4bib.github.io/pica/#/verarbeitung?id=validierung). Mainly implemented in https://metacpan.org/dist/PICA-Data/source/lib/PICA/Schema.pm

**Comment by nichtich** [comment]
Péter created an [additional format for data validation](https://github.com/pkiraly/metadata-qa-api#defining-schema-with-a-configuration-file). I think Avram validation is enough to start with but additional rules could be express by other means, e.g. filter syntax evaluating in a boolean expression.
