### ISSUE TITLE
Add beginner tutorial

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#211]

**Comment by a-wendler** [comment]
ich hab schon angefangen das tutorial zu schreiben. wo soll ich das nochmal ablegen?

**Comment by niko2342** [comment]
Ich habe die Infrastruktur für die Dokumentation mit [mdBook](https://rust-lang.github.io/mdBook/) angelegt. Du kannst Tutorial unter [docs/book/de/beginner-tutorial.md](docs/book/de/beginner-tutorial.md) ablegen. Wenn der Pull-Request im main-Branch ist, kann das Ergebnis als [HTML](https://deutsche-nationalbibliothek.github.io/pica-rs/book/index.html) aufgerufen werden.

**Comment by a-wendler** [comment]
@niko2342 Du müsstest mir für das Tutorial bitte nochmal erklären, was der praktische Unterschied zwischen == und === ist. Danke!

**Comment by niko2342** [comment]
Der `==`-Operator prüft, ob es ein Unterfeld gibt, dass einem Wert entspricht. `pica filter "012A.a == 'abc'"` liest sich wie folgt: Es existiert ein Feld `012A` mit einem Unterfeld `a` das gleich `abc` ist. Es könnten noch weitere Unterfelder `a` existieren, die nicht `abc` sind.

Im Gegensatz dazu stellt der `===` sicher, dass alle Unterfelder `a` gleich `abc`. `pica filter "012A.a == 'abc'"` liest sich wie folgt: Es existiert ein Feld `012A` bei dem *alle* Unterfelder `a` gleich `abc` sind.

Bei beiden Varianten ist es nicht ausgeschlossen, dass es noch ein weiteres Unterfeld `012A` gibt, dass kein Unterfeld `a` enthält.

**Comment by a-wendler** [comment]
Super. Danke. Das verstehe ich.

**Comment by a-wendler** [comment]
Könnte ich für das Tutorial mal Beispiele für #259 und #255 sehen? Mir ist nicht klar, was das macht und wie es funktioniert. Sonst ist der erste commit des Tutorials in meinem Fork im branch tutorial. Möglicherweise ist so schon reif ein erstes Pull Request.

**Comment by niko2342** [comment]
### Tag Pattern

Es kommt öfters vor, dass sich ein Wert vom gleichen Typ in unterschiedlichen Feldern befindet. Z.B. befindet sich im Feld `028A $9` die "Person, Familie - 1. geistiger Schöpfer" und im Feld `029A $9` "Person, Familie - weitere geistige Schöpfer". Um Datensätze zu filter, die entweder einen 1. geistigen Schöpfer oder einen weiteren geistigen Schöpfer haben, musste man bisher folgenden Filter schreiben:

```bash
$ pica filter "028A.9? || 029A.9?" DUMP.dat.gz
```
Mit der Einführung von #259 lässt sich der Ausdruck wie folgt vereinfachen:

```bash
$ pica filter "02[89]A.9?" DUMP.dat.gz
```
An jeder Position in einem Tag/Feld kann eine Liste der gültigen Werte angegeben werden. Es wird dann jede mögliche Kombination ausprobiert, um einen Match zu finden. Bsp. `0[12][34]A` führt zu der Liste `013A`, `014A`, `023A` und `024A`.

### Multiple Subfield Codes

Analog funktioniert #255. Beispiel: Im Feld `045E` befindet sich die Sachgruppe der Deutschen Nationabibliografie. Im Unterfeld `$e` die Hauptsachgruppe (HSG) und im Feld `$f` die Nebensachgruppen (NSG). Bin ich an allen Datensätzen interessiert, die zur HSG 100 oder zur NSG 100 gehören, musste man bisher folgenden Filter schreiben:

```bash
$ pica filter "045E.e == '100' || 045E.f == '100'" DUMP.dat.gz
```
Mit der Einführung von #255 lässt sich der Ausdruck wie folgt vereinfachen:

```bash
$ pica filter "045E.[ef] == '100'" DUMP.dat.gz
```
### Anmerkung

Beide Verfahren sind kombinierbar: `0[12]3[AB].[xyz]` ist ein gültiger Ausdruck.
