### ISSUE TITLE
Static selector values in select expressions

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#237]
example:

```bash
$ pica select "003@.0, 'abc'" 123456789X.dat
123456789X,abc
```

**Comment by a-wendler** [comment]
what do I need this for?

**Comment by niko2342** [comment]
If you want to add a context column. For example, the fields 041A.9 (subject headings according to RSWK) and 044H.9 (subject headings assing by an automatic process) both refere to an GND entity. If you want to create a single file containing all entities, you could run the following commands:

```bash
$ pica filter "041A/*.9?" DUMP.dat | pica select -H "idn,ctx,gnd_id" "003@.0,'RSWK',041A.9" > subject_headings.csv
$ pica filter "044H.9?" DUMP.dat | pica select "003@.0,'PROCESS1',044H.9" >> subject_headings.csv
$ cat subject_headings.csv
idn,ctx,gnd_id
0123456789A,RSWK,123456789
0123456789A,RSWK,23456789A
...
0123456789A,PROCESS1,34567689
```

Analyzing this single file (ex. using python pandas) may be more comfortable:

```python
import pandas as pd

df = pd.read_csv("subject_headings.csv")
rswk = df[df["ctx"] == "RWSWK]
print(rswk)
```

Note 1: The second filter/select command appends (`>>`) the content to the existing file.
Note 2: The `041A{9?, 'RSWK', 9}` syntax is not possible yet.

**Comment by a-wendler** [comment]
thank you. understood!
