### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by nwagner84** [deutsche-nationalbibliothek/pica-rs#246]
This issue collects ideas on how to improve the documentation. Some ideas:

- provide documentation in german
- #211
- Automation with shell scripts / Makefile
- Postprocessing with Python/Pandas
- API HOWTO
- Use Wiki?
- Link zu external documents (blog post about GND-Dashboard)
- Missing documentation (shell completion, config)
- More examples/demos
- ~~Use [mdBook](https://rust-lang.github.io/mdBook/index.html) for documentation~~ (#250)

**Comment by niko2342** [comment]
CC: @ramonvoges @a-wendler @san-uh

**Comment by nichtich** [comment]
If documentation for end-users should be written in German anyway, I'd be happy to make it part of the reference guide <https://pro4bib.github.io/pica/#/>. I am open to any suggestions and collaboration!
