### ISSUE TITLE
Rethink JSON serialization

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#249]
The [JSON serialization](https://github.com/deutsche-nationalbibliothek/pica-rs#json) differs from [PICA JSON](http://format.gbv.de/pica/json) and it uses yet another terminology (`name` instead of `tag` and `code` as the PICA documentation I know, or `id` as in [PPXML](http://format.gbv.de/pica/ppxml)). If yet another PICA serialization is needed, there should also be another name instead of "JSON" (e.g. PPJSON?). See existing PICA serializations as <http://format.gbv.de/schema/avram/specification>.

**Comment by niko2342** [comment]
Thanks for your comment. I'm thinking about CLI switches to change between different JSON formats (PICA JSON, DNB). The default should be PICA JSON.

**Comment by niko2342** [comment]
see https://github.com/serde-rs/serde/issues/766

**Comment by nichtich** [comment]
Is this JSON format actually used at DNB and is it stable? If so, I'd describe and include it at <http://format.gbv.de/pica>.

**Comment by nichtich** [comment]
We could add command `ndjson` to emit line-separated [PICA JSON](http://format.gbv.de/pica/json) but the documented workaround with `jq` is fine for me too. The only open question is whether to use pretty-printed JSON by default. The current documentation shows how to use `jq` for pretty-printing but you can't expect jq to be installed.
