### ISSUE TITLE
Common syntax to reference PICA fields, independent from content

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#271]
Split from #248. The syntax to select and filter PICA records or record content should be the same for all tools, at least for the basic use cases. The **most basic use case** is to reference a list of PICA fields, independent from their content.

In [PICA Path Expression](https://pro4bib.github.io/pica/#/formate?id=abfragesprache) (based on [MARCSpec](http://marcspec.github.io/MARCspec/marc-spec.html)) the current syntax is

    # tag                      # optional occurrence or occurrence range
    ([012.][0-9.][0-9.][A-Z@.])(\[([0-9.]{2,3}|[0-9]+-[0-9]+)\])?   

`[...]` instead of `/` was used for occurrences because MARCSpec already used `/` for substring ranges. These are mainly relevant to fixed width MARC fields (having no occurrences and subfields), and `/` is used before occurrences in [PICA Plain](https://format.gbv.de/pica/plain) anyway. So the common syntax can use `/` (partly breaking some backwards compatibility in Catmandu::PICA). Open Issues:

1. Wildcard characters in tags (PICA Path supports `.`)
2. Wildcard character in occurrences (PICA Path supports `.`)
3. Lists of fields (not part of PICA Path yet)

PICA Fields are often grouped in levels (first digit) and ranges (second and third digit) that's what wildcards in tags are mainly used for. Wildcard character in occurrences are less relevant because they can mainly be replaced by ranges. The `.` clashes with its use as subfield indicator (alternative to `$`) in pica-rs, so we could introduce `*` at the end of a tag instead. (e.g. `0*` for level 0 or `001*` for system tags on level 0). The syntax would then be (space for readability):

    (\* | [012] (\* | [0-9] (\* | ([0-9] ([A-Z@*]) ) ) )
    (\/ ([0-9]{2,3} | [0-9]{1,3} - [0-9]{1,3} ) )? 

Alternatively keep the `.` as wildcard.

Lists of multiple fields could be separated by `,`, `|` or any space character (?)

**Comment by niko2342** [comment]
I think it is not necessary to have a unified syntax for selecting fields/subfields. pica-rs provides a first set of syntax rules to express selection and projection operations. At the moment these two basic operations are enough, but I have already ideas to extend or change this syntax (template expressions, aggregation function, etc.).

**Comment by nichtich** [comment]
I fully agree, this was more an idea or duplicate. With #346 we have a common subset to reference fields and subfields (and optionally character ranges within subfield values). I've just updated [the specification](http://format.gbv.de/query/picapath) with more explanation (in German), minor details can still be discussed. PICA Path covers referencing as most important use case. Everything beyond (conditions, aggregations, mappings...) depends on particular tools.
