### ISSUE TITLE
Avoid clash of command (and option?) names with picadata CLI

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#274]
I've renamed picadata command `split` to `levels` because it served a different purpose than `split` in pica-rs and I decided to not name another command `select` for the same reason. This is the list of commands in picadata CLI 1.30 (no name clash so far):

* `convert`: Convert between PICA+ serialization formats (the default command).
* `get`: Print subfield values.
* `count`: Count number of records, holdings, items, and fields.
* `fields`/`subfields`/`sf`:  List distinct fields or subfields in the data. 
* `explain`: Lookup (sub)fields in an Avram schema.
* `validate`: Validate data against an Avram schema ("-s/--schema").
* `diff`: Compare PICA records from two inputs. Output is always annotated PICA Plain.
* `patch`: Apply modifications given in annotated PICA Plain.
* `build`: Build or extend an Avram schema from input data

Compatible command line options may be nice as well but more difficult to achieve without loosing flexibility. Nevertheless have a look at the [existing options](https://metacpan.org/dist/PICA-Data/view/script/picadata#OPTIONS) before adding new options.

Skimming though existing options in both tools I found the following differences:

* `--limit/-l` vs `--number/-n` are semantically equivalent. I can add an alias in picadata.
* `--path` in pica-rs seems to have different purpose than in picadata (?)
* `-s` is used for `--skip-invalid` in pica-rs but for `--schema` in picadata
* `-t` is used for `--template/--tsv/--threshold`,  in pica-rs but for `--to` (output format) in picadata
* `-f` is used for `--expr-file` in pica-rs but for `--from` (input format) in picadata (could be changed in pica-rs, as only used at one place?)

Main reason to avoid name clash is not to confuse use of both tools. It is also possible to let one tool (or another short script) wrap both to combine functionality.

**Comment by niko2342** [comment]
@nichtich The metacpan link seems to be broken ("Not found"). Can you provide the correct link?

**Comment by nichtich** [comment]
https://metacpan.org/dist/PICA-Data/view/script/picadata#OPTIONS should work - otherwise search for "picadata" at https://metacpan.org/.

**Comment by niko2342** [comment]
I think it is not practicable to unify command line options/flags between different pica tools. pica-rs provides a common command line interface to different commands, specialized for a particular task. but each command can be considered as an standalone tool, which needs a individual set of cli options and flags. Many of the namings are taken/inspired from/by established tools like grep, find, etc.

In the next year, the core commands enter the stabilization phase, where it is possible that the naming of cli options/flags may change. Therefore, I would like to keep this issue open and review it periodically.

**Comment by nichtich** [comment]
I'd only urge on adding short name `-n` for `--end` to be used like `head -n`, so closing this discussion.
