### ISSUE TITLE
Summary of skosifying the GND

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#277]
Show summary of skosifying the GND:
- number of `records` processed
- number of `concepts` created
- number of `prefLabels` created
- number of `altLabels` created
- number of `hiddenLabels` created
- number of `broader` relations created
- number of `related` relations created
- number of `labels` filtered created

**Comment by san-uh** [comment]
If possible, please also output the number of partial terminologies:

person, work, geography, conference, congress, subject

**Comment by niko2342** [comment]
This issue will be tracked in a new project.
