### ISSUE TITLE
Installation of 0.6.0 fails

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#287]
Installation via `cargo install --git https://github.com/deutsche-nationalbibliothek/pica-rs --tag v0.6.0 pica` fails because clap 3.0.0-beta.4 cannot be installed properly:

```
Compiling clap v3.0.0-beta.4
error: unexpected token: `include_str`
 --> /srv/apps/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `clap`
```

**Comment by niko2342** [comment]
Can you check your Rust version? Update to Rust 1.54.0 (or newer) should fix the problem. If you use `rustup`: just run `rustup update`.

**Comment by nichtich** [comment]
Thanks! Most recent version of Rust in Ubuntu 20.04 LTS (or [any newer version](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=rustc)) is Rust 1.51.0, not working neither. I can hack around to install a more recent version on my own machine but devops likely stick to the officially supported packages a Ubuntu LTS. This should be kept in mind to keep low the barrier to adoption.

**Comment by niko2342** [comment]
Alternatively, you can download the official release from https://github.com/deutsche-nationalbibliothek/pica-rs/releases/tag/v0.6.0, which was built with the latest Rust version and dependencies.

Please keep in mind, that pica-rs is not stable yet, but nevertheless I will add an comment to the readme.

**Comment by nichtich** [comment]
Thanks! And don't feel pushed :-)
