### ISSUE TITLE
Support to choose PICA Plain as input and output format

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#309]
I use to store PICA data in PICA Plain for easy inspection and analysis with command line tools and text editors. To make use of `pica-rs`, the records need to be converted between Normalized PICA+ and PICA plain, e.g.:

    picadata -t plus records.pp | pica filter -s "002@.0 =~ '^O'" | picadata -f plus -t plain
    picadata -t plus records.pp | pica filter -s "002@.0 =~ '^O'" | pica print   # equivalent

I would like to use [picadata options -t, --to and -f, --from](https://metacpan.org/dist/PICA-Data/view/script/picadata#OPTIONS) in `pica-rs` as well:

* Default value is `plus` (with alias `norm`) to read and write normalized PICA+ (as implemented)
* Parse PICA Plain when `--from` is `pp` or `plain` or input filename has file extension `.pp` or `.plain`
* Write PICA Plain when `--to` is `pp` or `plain` (as implemented with command `print`)
* If only `--from` is given, also use its value as `--to`

The example above would then not need the `picadata` script:

    pica filter -s "002@.0 =~ '^O'" records.pp
    pica filter -s "002@.0 =~ '^O'" -f plain < records.pp            # equivalent
    pica filter -s "002@.0 =~ '^O'" -f plain -t plain < records.pp   # equivalent

**Comment by nichtich** [comment]
Following [this comment](https://github.com/deutsche-nationalbibliothek/pica-rs/pull/359#issuecomment-986053471):

> I can understand that supporting more pica dialects could be a very useful (filter syntax), but I need more time to think about the implications for the software architecture. At this time, only PICA+ is supported as input dialect.

The input dialect is [normalized PICA+](https://format.gbv.de/pica/normalized) with one record per line. There is also [binary PICA+](https://format.gbv.de/pica/binary) with `0x1D` as record separator. I bet support of binary PICA would not be difficult because it is just a different byte code.

PICA Plain, as supported with command `print` is different not only because it uses a different byte code as subfield indicator (`$`) but also because dollar sign in subfield values needs to be escaped, so this may be more difficult. Nevertheless I prefer PICA Plain for large data sets because it can be used with line-oriented tools such as `tail` and `grep` to manually inspect records.

Support of PICA XML as input format is no priority because in this case you are slow anyway, so conversion with another tool should be fine. And PICA JSON is only used in Web applications.

**Comment by niko2342** [comment]
As I already mentioned, I need more time to think about the implications on the software architecture (dialect detection, configurable parser, cli interface, etc.). Furthermore, I want to refactor the parser code first, after generic associated types (GATs) are finally available in Rust.

**Comment by nichtich** [comment]
As `print` already emits valid PICA Plain (including proper escaping). Directly reading PICA Plain as well would be convenient but is no priority.

**Comment by nichtich** [comment]
Sorry for high traffic in this project but here is a script to convert PICA Plain (without error detection) to PICA Normalized:

~~~perl
  #!/usr/bin/perl
  while (<>) {
      chomp;
      print "\n" and next if $_ eq "";
      die "invalid PICA Plain at line $.: $_\n"
        if $_ !~ qr{^([012]\d\d[A-Z@](/\d+)?) \$(.+)};
      my $value = join '$', map { s/\$/\x1F/gr; } split '\$\$', $3;
      print "$1 \x1F$value\x1E";
  }
  print "\n";
~~~

Not very complex but complex enough to be more than a single line.

**Comment by niko2342** [comment]
@nichtich As you said in #445 pica-rs should focus on normalized PICA+.
