### ISSUE TITLE
Filter syntax: add negative regex match

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#310]
Add operator `!~` for negative regex match, e.g. `002@.0 !~ '^O'` (current workaround in this example: `002@.0 =~ '^[^O]'`).

**Comment by niko2342** [comment]
Good idea! I'm going to implement this feature in one of the next releases. Until then, maybe a invert match may help:

```bash
$ pica filter --invert-match "002@.0 =~ '^O'"
$ pica filter -v "002@.0 =~ 'O'"
```
