### ISSUE TITLE
Support negated character classes in a `TagMatcher`

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#313]
It should be possible to negate a character class in a tag matcher expression.  The expression `012[^A]` should match against all tags starting with `012` followed by any valid character in position 4, except `A` (`012B` is valid, `012A` is invalid`).

**Comment by nichtich** [comment]
This and #312 more and more reinvents regular expressions. The benefit compared to the additional complexity is low, especially if formal specification of PICA Path language (#346) is a goal.
