### ISSUE TITLE
Add detailed documentation for all commands

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#343]

**Comment by nichtich** [comment]
This includes documentation of options common to multiple commands. To get a current overview:

    for cmd in $(pica help | awk 'p{print $1}/^SUB/{p=1}'); do echo $cmd; pica help $cmd | sed '1,/^OPT/d | grep .'; done

Options currently available in more then two commands:

     14 --help (all)
     12 --skip-invalid (all but help, invalid)
     12 --output (all but help, partition)
      7 --gzip (all but help, completions, count)
      5 --translit (maybe needs discussion)
      3 --limit (could added to more commands, see https://github.com/deutsche-nationalbibliothek/pica-rs/issues/517#issuecomment-1385125351)
      3 --append (could be extened to all with --output)

**Comment by niko2342** [comment]
New command-line options should be discussion at the stabilization tickets for commands that are not stable yet (if the issue is not already closed, otherwise a new ticket should be filed).

In general, I like a high memorability of command-line options across different commands. But this should not be an end to itself and must be discussion for each command separatly.

The documentation is part of each single stabilization ticket, and therefore I close this ticket.
