### ISSUE TITLE
Web application playground

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#363]
It would be nice to analyze PICA+ data in a web application, especially commands `filter`, `frequency` and `select`. The applications goes beyond pica-rs because it also needs user interface and methods to store PICA data.

A quick draft how this could be done:

* decouple code of CLI and parsing/serializing from analysis and package the latter as module, compiled with WebAssembly (Rust)
* implement a local browser storage (IndexedDB or) for PICA data (JavaScript)
* add upload form and SRU import to read PICA data into the storage (JavaScript)
* add interface to show lists or records and result of frequency and select (JavaScript)
* use [PicaEditor](https://github.com/gbv/pica-editor#readme) to show individual records (JavaScript)

**Comment by nichtich** [comment]
A possibly easier alternative is a Jupyter notebook with pica-rs installed, to be used either via shell or Python-wrapper.

**Comment by niko2342** [comment]
I thought in a similar direction using pica-rs for data exploration und evaluation using a web-frontend (`serve` or `eval` command). I think that this must not be necessarily beyond pica-rs.

For such an experimental feature I would like to use more recent (cutting-edge) technologies like [Yew](https://yew.rs/), [Actix](https://actix.rs/), asynchronous communication  channels and a more effcient serialization than JSON oder XML (like cbor, protobuf).

But this are just ideas, there is currently no plan to implement such an new feature.
