### ISSUE TITLE
Reduce records to selected fields

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#365]
I want to use pica-rs to find and fix systematic errors caused by typos. Basically search-and-replace on large data sets. By now the speed advantage of pica-rs is dwarfed because it always emits full records, so the whole data set needs to be re-parsed. An example:

Some K10plus records have value `22 Arabic` in `045F$e` where it should be `22/ara`. pica-rs is great to find these records but further processing only requires fields `003@` and `045F`. This works:

    $ pica filter "045F.e == '22 Arabic'" k10plus.dat | picadata -f norm "003@,045F"
    003@ $0219119252
    045F $e22 Arabic$a236.1

but `picadata` needs to parse the full record. Reduction of the records in pica-rs would be faster, e.g.

    $ pica filter "045F.e == '22 Arabic'" k10plus.dat | pica reduce "003@,045F" | pica print
    003@ $0219119252
    045F $e22 Arabic$a236.1

or

    $ pica filter "045F.e == '22 Arabic'" --reduce "003@,045F" k10plus.dat | pica print
    003@ $0219119252
    045F $e22 Arabic$a236.1

**Comment by niko2342** [comment]
Thanks for you suggestions; this seems to be a useful feature, I'll add this issue to the product backlog. Also I re-open #169 wich could be a alternative approach for user, which are not fimilar with `picadata`.
