### ISSUE TITLE
Filter/Matcher optimization

### ISSUE THREAD

**Issue by nwagner84** [deutsche-nationalbibliothek/pica-rs#366]
- reorder boolean expression (move regex expr to the end of the expression)
- `((expr))` → `(expr)`
- `!!(expr)` → `(expr)`
- `012A.0 in ['abc']` → `012A.0  == 'abc'`
- `012A.0 == 'abc' || 012A.0 == 'def'` → `012A.0  in ['abc', 'def']`
- `012A.0 == 'abc' || 012B.0 == 'abc'` → `012[AB].0  == 'abc'`
- `012A.0 =~ 'A.*$'` | `012A.0 =~ 'A.*` → `012A.0 =^ 'A'`
- `012A.0 =~ 'A$'` | `012A.0 =~ '.*A$` → `012A.0 =$ ''A'`

**Comment by nichtich** [comment]
To me this looks like a case of "premature optimization"
