### ISSUE TITLE
PICA+ to SQL transformation

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#367]
Idea:

```
$ cat schema.def
"idn_bbg", "idn,bbg", "003@.0, 002@.0"
"idn_gold ", "idn,concept_id,label", "003@.0,041A/*{9?, 9, a}"

$ pica sql -s schema.def dump.dat -o dump.sql
```

Questions:

- SQL-Dialect (PostgreSQL, MySQL, ...)
- Additional infos like index columns, references, data types, ...

**Comment by nichtich** [comment]
This would go against decoupling of tools but would make a good example with an independent tool/script.

**Comment by niko2342** [comment]
Can you explain you point a little bit more. What do you mean with "against decoupling of tools"? If this idea is "against decoupling of tools", where is the difference to the `json` command, which also performs data conversation. Should the `json` and `xml` also be separated into single applications? 

pica-rs is a toolkit of independent tools which operates on normalized PICA+. Even when they share the same entry point (`pica` or `pica.exe`), the tools can be thought of independent from each other.

**Comment by nichtich** [comment]
> Should the `json` and `xml` also be separated into single applications?

Yes, see #587. A command to help setting up database may be useful but the target is fuzzy because it depends on database engine and requirements. Depending on use cases and features a search engine (Solr index) or NoSQL database or format such as #383 may better be suited.

**Comment by niko2342** [comment]
I close this issue, because there is no use-case at the DNB. Using the Apache Arrow format as input and output format is more important and using this format to populate a SQL is much easier.
