### ISSUE TITLE
Consider changing print colors

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#382]
With solarized light scheme, the result of `pica print` is not readable. I use green for subfield values in `picadata`. See comparision:

![grafik](https://user-images.githubusercontent.com/299856/148749900-8525a0ec-3788-4366-9002-4b1de347960c.png)

xterm

![grafik](https://user-images.githubusercontent.com/299856/148750041-f813e7eb-b94b-4611-bd55-a31e6d7c8de7.png)

solarized dark
![grafik](https://user-images.githubusercontent.com/299856/148750186-152c3847-3d25-44ac-ba45-612cb1250592.png)

**Comment by niko2342** [comment]
@nichtich I've changed the behavior of the `print` command. You can change the the colors and styles in your user-config (see #389 for an example).
