### ISSUE TITLE
Support Apache Arrow format

### ISSUE THREAD

**Issue by nwagner84** [deutsche-nationalbibliothek/pica-rs#383]
- https://github.com/apache/arrow-rs/blob/master/parquet/README.md
- https://en.wikipedia.org/wiki/Apache_Parquet

**Comment by nichtich** [comment]
Similar to #367 this might better be done in an independent tool, if needed at all.

**Comment by mfakaehler** [comment]
Personally, the data analysis workflow with pica-rs never ends in pica-rs for me. There is always a step, where I need to load the data into a program, to do some more tidying, reshaping etc.
I wouldn't turn pica-rs in a full data analysis software. However, I think there is a good argument to make, that pica-rs should offer interfaces that make downward analysis more convenient. CSV as an interface is quite universal, but has severe limitations, when in comes to read-in-time and disk space usage. 
In [2016](https://www.rstudio.com/blog/feather/) there was an initiative put forward by RStudio and Apache Arrow, that introduced the feather file format. This was developed as an on-disk file format to increase the interoperability between R and Python. By now I think it has matured as a file format and would be, similar to parquet, a good interface format to increase the usability of pica-rs in downward analysis. 
Generally, I believe [apache arrow](https://arrow.apache.org/) is a good direction to go, with regard to columnar interface formats.

**Comment by nichtich** [comment]
Oh, I did not know Apache Arrow, this looks interesting. I can imagine loading a dump into memory and querying it with `filter` and `select` as supported by command line from an input stream - actually this would be a PICA+ database such as CBS but with other capabilities and #363 could be an interface to it.  I'm curious about actual gain of speed in using in-memory database.
