### ISSUE TITLE
Transliteration für strings in Filterausdrücken

### ISSUE THREAD

**Issue by a-wendler** [deutsche-nationalbibliothek/pica-rs#436]
Bei String-Vergleichen in Filterausdrücken müssen Umlaute etc. als NFD eingegeben werden, damit sie korrekt matchen.
Es wäre schön, wenn pica-rs das automatisch oder mit Flag handeln würde.

**Comment by nichtich** [comment]
Ich finde pica-rs sollte alle Eingabe (Datensätze und Argumente) in eine Unicode-Normalform bringen und für die Ausgabe eine Option bieten, ob als NFD oder als NFC ausgegeben wird.

**Comment by nichtich** [comment]
Could be covered by existing option `--translit`.

**Comment by niko2342** [comment]
Die Option `--translit` ist für die Transliteration der Daten, die das `select` (oder `frequency`) Kommando erzeugen gedacht. Mein Ansatz für das Problem ist, dass in der `Pica.toml` die Normalform hinterlegt werden kann, in der die Daten vorliegen. Ist die Option gesetzt, werden die Filterausdrücke automatisch in die entsprechende Normalform (passend zu den Daten) transliteriert. Das hat den Vorteil, dass die Performance erhalten bleibt und keine UTF8-Validation (bspw. im `filter` Kommando) stattfinden muss.

Sollte es Nutzer*innen geben, bei denen der Dump in wechselnder Normalform vorliegt, dann würde ich im Zweifel auch eine neue Option hinzufügen, die aber anders als `--translit` heißt.

Die Anpassung werde ich aber erst machen, wenn auch die neue Matcher-Engine im Filter-Kommando umgesetzt ist.
