### ISSUE TITLE
File output corrupt

### ISSUE THREAD

**Issue by a-wendler** [deutsche-nationalbibliothek/pica-rs#438]
When saving with `pica print -o` over an existing file the output can be corrupted if the new file is shorter than the old one. The old file is not fully replaced but only overwritten with the new data with the overlap of the old file staying in the file.

Solution: files should be completely replaced if the file already existed before.

Problem in the attached file starts in line 5368. File is result of same filter, first time without `--reduce`, second time with
[ii-exemplare.txt](https://github.com/deutsche-nationalbibliothek/pica-rs/files/8207396/ii-exemplare.txt) File was originally saved as .dot, only renamed to be uploadable here.

**Comment by niko2342** [comment]
@a-wendler Thanks for this bug report. Almost all of the commands were affected by this bug, which was introduced in version 0.10.0.

Fixed in [v0.11.0](https://github.com/deutsche-nationalbibliothek/pica-rs/releases/tag/v0.11.1).
