### ISSUE TITLE
Unexplainably wrong filter expression

### ISSUE THREAD

**Issue by a-wendler** [deutsche-nationalbibliothek/pica-rs#443]
Please help! What is wrong with this filter expression?
`pica filter "(209A/*.a =^ 'Bö' || 209A/*.a =^ 'Boe') && 011@.a =~ '^([01xX][0-7x][0-9xX][0-9xX])|([01xX][8][12][0-9xX])|([01xX][8][3][0])'"`

The two groups connected with && work independently but not together. I've used that same regex expression in another combined filter and it worked fine.

**Comment by a-wendler** [comment]
The same expression works if  the two groups are connected via `--and` as in:

`pica filter "209A/*.a =^ 'Bo<0308>' || 209A/*.a =^ 'Boe'" --and "011@.a =~ '^([01xX][0-7x][0-9xX][0-9xX])|([01xX][8][12][0-9xX])|([01xX][8][3][0])'"`

**Comment by mschumac** [comment]
This should be a similar problem which only occurs when bracketing the first of several terms of an expression in curly brackets. Accepted (pica 0.12.0):

```
pica filter -s "010@{a == 'ger'}" /srv/aen-data/pica/DUMP.dat.gz
pica filter -s "010@{(a == 'ger')}" /srv/aen-data/pica/DUMP.dat.gz
pica filter -s "010@{a == 'ger' && (a == 'ger')}" /srv/aen-data/pica/DUMP.dat.gz
pica filter -s "010@{(a == 'ger')}" --and "010@{(a == 'ger')}" /srv/aen-data/pica/DUMP.dat.gz
pica filter -s "(010@.a == 'ger') && (010@.a == 'ger')" /srv/aen-data/pica/DUMP.dat.gz
```

Rejected with "error: invalid filter":

```
pica filter -s "010@{(a == 'ger') && a == 'ger'}" /srv/aen-data/pica/DUMP.dat.gz
pica filter -s "010@{(a == 'ger') && (a == 'ger')}" /srv/aen-data/pica/DUMP.dat.gz
```

But all of these pointless expressions should be valid.
