### ISSUE TITLE
read pica xml

### ISSUE THREAD

**Issue by c-poley** [deutsche-nationalbibliothek/pica-rs#445]
Es wäre wünschenswert, wenn pica-rs auch pica-xml verarbeiten (und nicht nur ausgeben kann). Damit ließen sich Datensätze von der DNB-SRU-Schnittstelle verarbeiten und auswerten, ohne auf einen neuen Dump zu warten.

**Comment by nichtich** [comment]
Die SRU-API muss doch sowieso noch angesprochen werden, wäre da nicht Catmandu die bessere Lösung, um Datensätze abzurufen und als normalisiertes PICA abzuspeichern?

**Comment by c-poley** [comment]
Das sind aus meiner Sicht zwei verschiedene Dinge:
(1) Abholen von Daten (welche auch immer via SRU-Schnittstelle)
(2) Verarbeiten pica-xml, das nicht unbedingt via SRU kommen muss.
Ich gebe Dir Recht, dass man sich da auch mit anderen Hilfsmitteln wie Catmandu behelfen kann. Wenn es eine einfache und generische Implementierung für (2) in pica-rs gibt, dann muss man nicht noch eine weitere Technologie (wie perl) benutzen, um solche Datendumps auszuwerten. Wenn pica-rs schlussendlich den http-Request (1) optional ausführen kann, dann wäre es perfekt.

Syntax etwa: pica filter -s "002@.0 =^ 'Oa'" -input xml https://services.dnb.de/sru/dnb?version=1.1&operation=searchRetrieve&recordSchema=PicaPlus-xml&maximumRecords=100&query=idn%3D1011533391%20or%20idn%3D1010587420%20or%20idn%3D1011700263

**Comment by nichtich** [comment]
Ohne SRU-Client musst du die URL selber zusammenbauen mit URI-Escaping und das Ergebnis is mitunter unvollständig (`maximumRecords`), das ist *ziemlich* fehleranfällig. Die Beispiel-URL einer SRU-Abfrage liefert zudem kein PICA/XML sondern SRU-XML in das PPXML (eine von zwei XML-Serialisierungen von PICA) eingebettet ist, das ist alles etwas komplizierter.

PICA Catmandu löst die Aufgabe "Abfrage per SRU" und "Konvertierung in Gewünschte PICA-Varianten" mit allen Stolperfallen, ist eigentlich etabliert und dass es in Perl implementiert ist, ist bei Verwendung als Kommandozeilenprogramm eigentlich egal.

Gäbe es  SRU-Client library in in Rust, könnte mit einigem zusätzlichen Aufwand so etwas umgesetzt werden:

`pica filter -s "002@.0 =^ 'Oa'" --url https://services.dnb.de/sru/dnb --cql "idn=1011533391 or idn=1010587420 or idn=1011700263"`

Gibt es aber nicht.

**Comment by nichtich** [comment]
Ich denke mittlerweile dass es besser wäre wenn pica-rs als Eingabe-Format nur normalisiertes PICA+ unterstützt, da es einfach zu viele verschiedenen Serialisierungen und damit Fehlermöglichkeiten gibt. Die Erstellung von normalisiertem PICA+ mit anderen Werkzeugen sollte weiter dokumentiert werden, dieser Schritt gehört jedoch eher zum Schritt der Datenbereitstellung (Extract) während pica-rs seine Stärken bei der die Analyse und Konvertierung ausspielt. Nach schon zwei Generationen von PICA-Kommandozeilentools die ich in Perl entwickelt habe, denke ich dass es besser ist nicht zu viele Funktionen in ein Werkzeug zu packen.

Das heisst dieses Issue und Issue https://github.com/deutsche-nationalbibliothek/pica-rs/issues/309 sollten geschlossen werden.

**Comment by niko2342** [comment]
Lieber @c-poley,

ich denke zwar, dass auch hier Rust einen entscheidenden Vorteil hat, aber dieses Feature nicht so richtig in pica-rs gehört. Um dieses Feature sauber umzusetzen, müsste eine generische Parser-Variante entwickelt werden. Das wäre machbar, spannend aber mit Sicherheit sehr zeitintensiv.

Wenn nichts dagegen spricht, würde ich das Ticket schließen.

**Comment by c-poley** [comment]
Eine generische Parser-Variante wäre etwas für später. Schließe daher das Ticket gern.
