### ISSUE TITLE
Remove selected fields

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#461]
Argument `--reduce` reduces records to a set of wanted fields (#365) but how to remove selected fields and keep the rest?

**Comment by niko2342** [comment]
Currently, it's not possible. I'm going to implement this feature within the next weeks.

**Comment by nichtich** [comment]
How about parameter `--remove` given a list of fields?

**Comment by niko2342** [comment]
I'll add RFC on how this should implemented soon, but this will be implemented after the transition the the new `pica-record` and `pica-matcher` crate.

**Comment by niko2342** [comment]
The new parameter will be named `--drop` and this feature gets implemented in #595 . (Note: The `--reduce` option is renamed to `--retain`).

**Comment by niko2342** [comment]
Sorry for the hasty decision: `--reduce` will be renamed to `--keep` (`-k`) and the new option will be named `--discard` (`-d`).

**Comment by niko2342** [comment]
This changed is part of the release `0.15.0`.
