### ISSUE TITLE
Stabilize `invalid` command

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#506]
Tracking issue for stabilizing the `invalid` command.

## Features

_No new features during command stabilization._

## Documentation

* [x] #500 
* [x] #525 

## Internals

* [x] #522 
* [x] #523
* [x] #524

**Comment by nichtich** [comment]
The documentation is misleading. This command does not "filter out invalid records" but it "prints invalid input lines" which which can't be decoded as normalized PICA+.

**Comment by niko2342** [comment]
@nichtich Thanks for your comment;  I rephrased the documentation (see #572).
