### ISSUE TITLE
Stabilize `completions` command

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#508]
Tracking issue for stabilizing the `completions` command.

## Features

TBA

## Documentation

- [ ] Add/Review CLI documentation
- [ ] Add/Review Documentation

## Internals

- [ ] Add snapshot tests

**Comment by nichtich** [comment]
The README.md should include a section on this command and link to documentation what do do with the output (one paragraph), e.g. https://github.com/scop/bash-completion#faq for bash, e.g. minimal: 

----

The `completions` command generates a completion file to enable command line completion. The output must be written to a file with name and location depending on the command line shell.

----

See also https://github.com/deutsche-nationalbibliothek/pica-rs/blob/main/docs/book/src/de/guide/cmds/completions.md and #574
