### ISSUE TITLE
Stabilize `partition` command

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#512]
Tracking issue for stabilizing the `partition` command.

## Features

_n/a_

## Documentation

- [x] Add/Review CLI documentation

## Internals

- [x] Switch to new `pica-record` crate
- [x] Add snapshot tests

**Comment by nichtich** [comment]
Documentation should tell what happens to records that don't have the specified subfield. Omitted or just `.dat` (looks like a hidden file but makes sense). Possibly add optional `--prefix` to all file names to avoid empty string name?

**Comment by niko2342** [comment]
@nichtich I've update the documentation (README/`--help`).

An option `--prefix` is not necessary, just use the existing `--template` option to change the filename:

```bash
$ pica partition -s --template "BBG_{}.dat" "002@.0" DUMP.dat.gz -o outdir
$ tree outdir
outdir
├── BBG_Aa.dat
├── BBG_Aal.dat
├── BBG_Aan.dat
├── ...
```
