### ISSUE TITLE
Add citation information

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#533]
https://citation-file-format.github.io/

**Comment by nichtich** [comment]
See https://github.com/deutsche-nationalbibliothek/pica-rs/pull/576 but `version` and `date-released` should be updated automatically. Same applies to outdated package information in `Cargo.toml` (`version` and `edition`). The version number is also mentioned in `README.md`. One of this three should be the source of truth to update the other.
