### ISSUE TITLE
pica filter crashes if input record has no PPN

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#568]
After processing 150GB PICA+ records crashed regularly I tried to pin down the input that caused pica-rs to stop working. The error message is:

    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bin/pica/commands/filter.rs:247:39

The error is triggered when a record without PPN (`003@ $0`) is read. Don't ask me how such records make it into our data dump  but pica-rs should not crash but process the record (unless allow_list is not empty).

**Comment by niko2342** [comment]
Yes, `pica filter` must handle this case properly, I'll open a PR soon.

**Comment by niko2342** [comment]
This bug is fixed in [v0.14.1](https://github.com/deutsche-nationalbibliothek/pica-rs/releases/tag/v0.14.1)
