### ISSUE TITLE
Merge and squash of selector outcomes

### ISSUE THREAD

**Issue by nwagner84** [deutsche-nationalbibliothek/pica-rs#583]
- Responsible: @niko2342 
- Status: accepted
- Feature PR: #642 

## Summary

As mentioned in #490 the multiplication of the rows of selector outcomes should be disabled in some cases. This could be achieved by two new operations: merging of fields (**merge**) and squashing of subfield values (**squash**).

## Details

To get the desired result two cases must be considered. First, all fields, which the *selector* points to, are *merged* into a single field simply by concatenating the subfield values of the subfield list. The information lost of the context (field) is expected anyway. The advantage is quite obvious, a selector produces a single outcome, because there is just one field left. The optional parameter name is `--merge`.

In the second step, all subfield values must be *squashed*  into a single value by intersperse the separator between the subfield values. This separator can be set by the optional parameter `--separator`, which is `|` by default. The optional parameter name is `--squash`.

The following example squashes all subfield values `$a` of the field `010@` into a single value. This results in a single line for each field, because fields are *not merged*:

```bash
$ pica select --squash "003@.0, 010@.a" DUMP.dat
012345679X,ger|eng
012345679X,ger|mul
```

In this example, only the `044H` fields are processed, which meets the subfield filter criteria. All subfields `$9` are added to the first `044H` field. After this is done, the subfield values will be squashed into a single value using the separator `,`:

```bash
$ pica select --squash --merge --separator "," "003@, 044H/*{9 | b == 'GND' && 9?}" DUMP.dat
012345679X,"23456789,34567890,456789X"
```

It may happen that the separator is part of a subfield value. In this case the commands stops and prints an error to the terminal (`stderr`). This behavior can be disabled explicitly by setting the `--ignore-squash-errors` flag. If this flag is set, the command prints an error to `stderr` but do not stop. 

The default is intended in order to prevent wrong results in an subsequent data analysis.

```bash
$ pica select --squash --separator "X" "003@, 044H/*{9 | b == 'GND' && 9?}" DUMP.dat
error: squash separator in subfield value

$ pica select --squash --separator "X" --ignore-squash-errors \
      "003@, 044H/*{9 | b == 'GND' && 9?}" DUMP.dat
error: squash separator in subfield value
012345679X,23456789X34567890X456789X
...
```

## Implementation

The **merge** operation should be implemented as an new operation on records (like the reduce option), because this feature might be an useful extension to the `filter` command. If this is too complicated the operation is implemented in the `select` logic. The **squash** operation affects only the selector outcome.

As with most new command-line options, short flags for `--merge` and `--squash` will be introduced later.

This features should be implemented after moving the select code into an separate crate and after the transition to the new `pica-record` parser.

## Related Issues

- #490
- #515

**Comment by nichtich** [comment]
Having *both* `merge` and `squash` options seems very complex. I still don't fully understand its consequences from your description.

- The option should have *one* name only: squash, merge, join, together...
- Option `--separator` with default value `|` seems fine. Please support `--separator ""` (empty string) as well!
- Having a subfield value with the separator in it should not be an "error" so `--ignore-squash-errors` should be removed or replaced. It may be a "conflict" at most and a warning may be given if explicitly requested for.

A select expression consists of a non-empty list of selectors `a`, `b`..`n`, each resulting in zero or more values. The question is how to transform this to a list or rows with *n* columns. I can imagine three reasonable variantes:

1. The current implementation uses the [cartesian product](https://en.wikipedia.org/wiki/Cartesian_product)
2. Suggested in #490 was to combine all values for each selector by concatenating with a separator
3. Another idea would be to get the first value only

In addition selector could be processed differently, e.g. cartesian product of selector 1, combined selector 2 and first value of selector 3 - but I doubt there is a need for it. I'd be fine with just having 1. and 2. The third variant may be better solved with extension of select syntax to state that only the first *x* value(s) are wanted.

**Comment by mschumac** [comment]
Da `merge` den `squash`-Schritt schon zu beinhalten scheint, schließlich produziert `select --merge` allein ja schon die Ausgabe mit Trennzeichen `|`, reicht nach meinem Dafürhalten die `merge`-Option aus. Es ist für mich nicht entscheidend, ob die Vereinigung aus einem wiederholten Unterfeld desselben Feldes oder einem wiederholten Feld heraus resultiert. Wäre die genaue Zuordnung der Werte zu den Feldern wichtig, würde man ja auf das herkömmliche `select` mit dem kartesischen Produkt ohne `--squash` und `--merge` zurückgreifen.

Gut finde ich an der Implementierung, dass nicht bereits eine Kürzung auf unterschiedliche Werte erfolgt, sondern alle Unterfeldinhalte inklusive Duplikate beibehalten werden und dadurch an Unterfeldern nichts verloren geht.
