### ISSUE TITLE
Concatenate records without duplicates

### ISSUE THREAD

**Issue by nwagner84** [deutsche-nationalbibliothek/pica-rs#585]
- Responsible: @c-poley 
- Status: accepted
- Feature PR: #628 

## Summary

The `cat` command should provide an `--unique` (`-u`[^1]) option in order to concatenate records without duplicates. 

## Details

The exists an interesting symmetry between the `partition` and `cat` command: The `cat` command can be used to reverse the partition process, but only if the partitions are distinct sets of records. With a new option `--unique` the `cat` command only write records, which are not already written.

The following example creates partitions over the language codes of a record. Because a record can have more than one code, the partitions are very likely not distinct and concatenating them would result in duplicate records. Using the `--unique` flag, no duplicates are written:

```bash
$ pica partition -s "010@.a" DUMP.dat -o partitions
$ pica cat --unique partitions/ger.dat partitions/eng.dat -o ger_eng.dat
```

The extreme case is to concatenate a file (without invalid records) to itself, which gives back the original set of records, because no duplicates are written and pica-rs preserves the order of records:

```bash
$ pica cat --unique DUMP.dat DUMP.dat -o out.dat
```

## Implementation

The list of seen records should be tracked in an `BTreeSet` with a hash of the record. Maybe this can be implemented in the writer component, for reusability in other commands.

[^1]: To keep command-line arguments consistent across different comamnds, the short variant can be introduced (like in the `select` command).

**Comment by nwagner84** [comment]
Idea: Use different methods to detect duplicates: hash or idn.

**Comment by nichtich** [comment]
Idea: use PPN as  uint32 (remove last character, it's a check-digit) and track duplicates via `BTreeSet` of `Range` to support large record sets.

**Comment by nwagner84** [comment]
I think this sounds very complicated: strip the last digit, parse an integer (which may fail), build and update ranges of PPNs coming in random order. This might be the best solution for your use-case in #614 but I'll start with a straightforward implementation using a `BTreeSet` of byte slices or byte strings.

After this is implemented you can start an experiment using your approach. Then we should measure the performance of different scenarios (best-case, worst-case, etc.).
