### ISSUE TITLE
Convert between PICA serialization formats

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#587]
PICA+ is used in several different serialization forms, I've seen and worked with at least seven:

* [Binary PICA](https://format.gbv.de/pica/binary)
* [Normalized PICA](https://format.gbv.de/pica/normalized)
* [PICA JSON](https://format.gbv.de/pica/json)
* [PICA Plain](https://format.gbv.de/pica/plain)
* [PICA XML](https://format.gbv.de/pica/xml)
* [PICA import format](https://format.gbv.de/pica/import)
* [PPXML](https://format.gbv.de/pica/ppxml)

Primary task of pica-rs toolkit is data analysis and the format used to read and write PICA+ is Normalized PICA on purpose for multiple reasons (simplicity, performance, maintanability...). Nevertheless PICA+ data happens to be used in other formats as well, so converting between formats should be possible.

## Proposed solution

- Add an independent command to convert between PICA+ serialization formats, in particular from and to Normalized PICA. The command *should not* support additional options other than input/output format to keep it simple and to not confuse functionality with pica-rs but it *may* later be added as command to pica-rs.
- Define name and options of the command
- Remove current beta commands [xml](https://github.com/deutsche-nationalbibliothek/pica-rs/issues/519) and [json](https://github.com/deutsche-nationalbibliothek/pica-rs/issues/518) (the latter is no standard format and should be renamed anyway).

Possble name and calling syntax (to be discussed):

~~~
pica-convert $format    # convert from $format to normalized PICA+
pica-convert to $format # convert from normalized PICA+ to $format
pica-convert $a to $b   # convert between format $a and $b
~~~

Additional arguments can be filename(s), or input from STDIN by default. Calling without arguments should show help. Default input format could also be detected from file extension, if not specified explicitly.

## Alternatives and workarounds

The [picadata](https://pro4bib.github.io/pica/#/picadata) tool can be used to convert to and from Normalized PICA, so support of other formats is not strictly needed in pica-rs. Better performance than using picadata can be achieved with ad-hoc conversion scripts [like this](https://github.com/deutsche-nationalbibliothek/pica-rs/issues/309#issuecomment-1396851452).

**Comment by niko2342** [comment]
I like the idea to start with a separate tool and I strongly recommend to evaluate [serde](https://serde.rs/) for the serialize/deserialize part. I suggest to add this idea to the agenda and discuss further steps in a separate meeting.
