### ISSUE TITLE
Support " for literal strings in filter and select

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#589]
Literal strings in subfield filters are enclosed in `'`. To pass this expression at command line it needs to be put into a string e.g. 

    pica filter "010@.a in ['ger', 'eng']"

Shell strings with `"`, however are not taken literally but characters such as `$`, `#`, and `!` have special meaning (string interpolation). To be safe a string can be given with `'` but then the literal value `'` cannot be used anymore. Workarounds:

    pica filter '010@.a in ['\'ger\'', '\'eng\'']'
    pica filter '010@.a in ['"'ger'"', '"'eng'"']'

How about support of strings enclosed in `"` as well so this will work:

    pica filter '010@.a in ["ger", "eng"]'

**Comment by nwagner84** [comment]
This feature is implemented in #612 . Support of double quotes in select expressions will become available soon; this requires migration to the new matcher engine first.
