### ISSUE TITLE
More helpful error message on Parse Pica Error

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#609]
Reading an invalid record results in a Parse Pica Error (unless surpressed with `--skip-invalid`) but making sense of it and finding the invalid record in input data is difficult.

**Describe the solution you'd like**

I suggest to add an input line number to the error message and to change the output format of byte array to hexadecimal (it can directly be converted with standard unix tool `xxd`).

Example error message:

    Parse Pica Error: invalid record in line 184523 (expected valid record, got: 30 30 31 40 20 1f ...

Instead of current

    Parse Pica Error: invalid record (expected valid record, got `[48, 48, 49, 64, 32, 31 ...

**Describe alternatives you've considered**

I converted the list of byte codes to a string with a Perl script and grepped for the content to find the invalid record in the input file.

**Comment by nwagner84** [comment]
I changed the verbose error message to a simpler format (see #643). Now, the line number (counts from 0) is printed as well as the filename or `stdin` if the record was read from standard input. The raw data isn't printed to the terminal; it's up to the user to find the line and inspect what's wrong with the record ( #526 might be a tool in the future).
