### ISSUE TITLE
truncation for pica filter

### ISSUE THREAD

**Issue by jaohbib** [deutsche-nationalbibliothek/pica-rs#769]
I would like to  get a list of all records containing   any value in 039D.9 .

i tried  multiple combinations like

pica filter -s '039D.9 == ".* "' first1kk

i know first1kk contains some matching records 

thanks 
for your help

**Comment by nwagner84** [comment]
Hi @jaohbib,

please try the following command:

```console
$ pica filter -s '039D.9?' first1kk -o 039D_9.dat
```

This expression gets all records, with at lease one filed `039D` with a subfield `9` and writes the output to `039D_9.dat`.

**Comment by jaohbib** [comment]
This works thanks  how is the filter syntax implemented is there more documentation i could read to avoid  such questions in the future

**Comment by nwagner84** [comment]
You can check the command reference (in german) for examples, especially [filter](https://deutsche-nationalbibliothek.github.io/pica-rs/book/docs/kommandos/filter/) command. Unfortunately, the chapter about the filter syntax is currently written and not done yet. It will be published within the next months.
