### ISSUE TITLE
How to reference fields of a given copy

### ISSUE THREAD

**Issue by jaohbib** [deutsche-nationalbibliothek/pica-rs#770]
I  have a pica record with multiple copys 

101@ $a 20
101U $0 utf8
201B/01 $0 15-04-13 $t 16:54:12.000
201U/01 $0 utf8
202D/01 $0 15-04-13 $b 1008 $a 0084
203@/01 $0 653124287
208@/01 $a 22-06-04 $b x
209R/01 $S 1 $u http://d-nb.info/962721840
101@ $a 21
101U $0 utf8
201B/01 $0 14-01-14 $t 19:41:03.000
201U/01 $0 utf8
202D/01 $0 14-01-14 $b 6277 $a 0046
203@/01 $0 659550679
208@/01 $a 12-08-04 $b z
209C/01 $a OLRD $x 00
209R/01 $u http://d-nb.info/962721840/34
101@ $a 22
101U $0 utf8
201B/01 $0 25-02-11 $t 06:48:41.000
201U/01 $0 utf8
202D/01 $0 25-02-11 $b cbs_97 $a 1999
203@/01 $0 554825236
208@/01 $a 07-05-02 $b xu
209O/01 $a SUBolrd $x 00
209R/01 $S 1 $u http://deposit.ddb.de/cgi-bin/dokserv?idn=962721840
101@ $a 30
101U $0 utf8
201B/01 $0 12-06-05 $t 12:54:47.000
201U/01 $0 utf8
202D/01 $0 12-06-05 $b touchtitle $a 0104
203@/01 $0 719589916
208@/01 $a 14-05-05 $b z
209C/01 $a OLRD $x 00
209R/01 $S 1 $u http://deposit.ddb.de/cgi-bin/dokserv?idn=962721840
101@ $a 40
101U $0 utf8
201B/01 $0 25-01-11 $t 11:16:26.000
201U/01 $0 utf8
202D/01 $0 25-01-11 $b r40sel4 $a 1999
203@/01 $0 578429039
208@/01 $a 31-03-03 $b xsn
209R/01 $S 1 $u http://webdoc.sub.gwdg.de/ebook/w/2002/pub/bio/01H004/of_index.htm

I only want to export or filter fields of copy belonging to a given iln  
is this possible ?

thanks

**Comment by nwagner84** [comment]
Hi @jaohbib,

it's not possible to filter for specific fields which belongs to a copy
of an ILN. You have to split the record first: Please take a look at the
**experimental** `explode`[^1] command.

Regarding your example: You have to split the record first and filter
for records which belongs the a given ILN:

```console
$ pica explode -s local DUMP.dat --where '010@.a == "20"' -o out.dat
$ pica explode -s copy DUMP.dat --where '010@.a == "20"' -o out.dat
```

The first command creates a new dump, containing only records with all
copies of ILN `20`. The second command creates a new dump, containing
records for each copy of an ILN-`20` section; all other records/copies
will be discarded.

NB: There is a known bug, that fields (except `101@`) of the local level
are not processed correctly. This bugfix is still on the TODO-list. This
could affect your use case.

[^1]: See https://deutsche-nationalbibliothek.github.io/pica-rs/book/docs/kommandos/explode/

**Comment by nwagner84** [comment]
Hi @jaohbib,

can I close this issue? Do you need more help?

// nico

**Comment by jaohbib** [comment]
I am still working on it

**Comment by jaohbib** [comment]
I use 
pica explode -s copy DUMP.dat --where '101@.a == "20"' -o out2.dat

to get only my copies but I receive only an empty file .  Is this another bug or is there a Problem with my data

I Added   a minimal Dump file containing a single record.



[DUMP.txt](https://github.com/deutsche-nationalbibliothek/pica-rs/files/15245350/DUMP.txt)

**Comment by nwagner84** [comment]
Ok, this is releated to the bug I mentioned. I took a look into the code, and I think I can fix this soon.

**Comment by nwagner84** [comment]
The bugfix #784 will be part of the next pica version.

**Comment by jaohbib** [comment]
The next Version of Pica or the next Version of Pica rs ist there a timeframe i can expect
________________________________
Von: Nico Wagner ***@***.***>
Gesendet: Mittwoch, 29. Mai 2024 10:31:25
An: deutsche-nationalbibliothek/pica-rs
Cc: jaohbib; Mention
Betreff: Re: [deutsche-nationalbibliothek/pica-rs] How to reference fields of a given copy (Issue #770)


The bugfix #784<https://github.com/deutsche-nationalbibliothek/pica-rs/pull/784> will be part of the next pica version.

**Comment by nwagner84** [comment]
I think the new release will be ready by the end of the week.

**Comment by nwagner84** [comment]
Hi @jaohbib, is this issue still relevant or can I close the issue?

**Comment by jaohbib** [comment]
This can be closed

Von: Nico Wagner ***@***.***>
Gesendet: Sonntag, 1. September 2024 09:43
An: deutsche-nationalbibliothek/pica-rs ***@***.***>
Cc: jaohbib ***@***.***>; Mention ***@***.***>
Betreff: Re: [deutsche-nationalbibliothek/pica-rs] How to reference fields of a given copy (Issue #770)


Hi @jaohbib<https://github.com/jaohbib>, is this issue still relevant or can I close the issue?

-
