### ISSUE TITLE
filter on missing values

### ISSUE THREAD

**Issue by jaohbib** [deutsche-nationalbibliothek/pica-rs#780]
I would like to filter any records where a given field is not filled

can i use truncation and inverse matching  for this ?

thanks

**Comment by nwagner84** [comment]
Hi @jaohbib,

you can negate the existence (`?`)-operator. For example, to get all records without a `021A` field use:

```console
$ pica filter "!021A?" DUMP.dat.gz -o no-021A.dat
```

NB: If you are working on Linux/Unix, it might be necessary to escape the `!`-sign depending on your shell (or you use single-quotes for the complete filter expression `pica filter '!021A?' DUMP.dat.gz`).

**Comment by nwagner84** [comment]
Hi @jaohbib, can I close this issue or is it still relevant?

**Comment by jaohbib** [comment]
This can be closed


Von: Nico Wagner ***@***.***>
Gesendet: Sonntag, 1. September 2024 09:41
An: deutsche-nationalbibliothek/pica-rs ***@***.***>
Cc: jaohbib ***@***.***>; Mention ***@***.***>
Betreff: Re: [deutsche-nationalbibliothek/pica-rs] filter on missing values (Issue #780)


Hi @jaohbib<https://github.com/jaohbib>, can I close this issue or is it still relevant?

-
